name: app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: any # DI
  dio: ^4.0.0
  google_sign_in: any
  http: any
  url_launcher: ^6.0.10
  email_validator: ^2.0.1
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  module:
    androidX: true
    androidPackage: com.example.app
    iosBundleIdentifier: com.example.app
