name: app_noticia
description: WNews

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: any
  provider: any # DI
  dio: any
  # google_sign_in: any
  http: any
  url_launcher: any
  email_validator: any
  shared_preferences: any
  comment_box: any
  flutter_launcher_icons: ^0.8.0
  image_picker: any


flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/user.png

  module:
    androidX: true
    androidPackage: com.example.app
    iosBundleIdentifier: com.example.app

